// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vet_api_Net.Data;

#nullable disable

namespace vet_api_Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510222057_AddBcvDollarAndFechaToMoneyType")]
    partial class AddBcvDollarAndFechaToMoneyType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_spanish2_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("vet_api_Net.Models.AlertasInterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccionRequerida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("accion_requerida")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("Completada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completada")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("DestinatarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("destinatario_id");

                    b.Property<string>("DestinatarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('admin','doctor','secretaria','todos')")
                        .HasColumnName("destinatario_rol")
                        .HasDefaultValueSql("'todos'");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_lectura");

                    b.Property<DateOnly?>("FechaLimite")
                        .HasColumnType("date")
                        .HasColumnName("fecha_limite");

                    b.Property<bool?>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("leida")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("LeidaPor")
                        .HasColumnType("int(11)")
                        .HasColumnName("leida_por");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('baja','media','alta','urgente')")
                        .HasColumnName("prioridad")
                        .HasDefaultValueSql("'media'");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTabla")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("referencia_tabla");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('stock_bajo','producto_vencido','cita_pendiente','tarea_admin','factura_pendiente','seguimiento_medico','sistema')")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DestinatarioId" }, "destinatario_id");

                    b.HasIndex(new[] { "FechaLimite" }, "idx_fecha_limite");

                    b.HasIndex(new[] { "Leida", "Completada", "Prioridad" }, "idx_pendientes");

                    b.HasIndex(new[] { "DestinatarioRol" }, "idx_rol");

                    b.HasIndex(new[] { "LeidaPor" }, "leida_por");

                    b.ToTable("alertas_internas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.CategoriasProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("categorias_productos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('programada','completada','cancelada','no_asistida','en_curso')")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'programada'");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cita");

                    b.Property<TimeOnly>("HoraCita")
                        .HasColumnType("time")
                        .HasColumnName("hora_cita");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("mascota_id");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int?>("SecretariaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("secretaria_id");

                    b.Property<string>("TipoCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('consulta','vacunacion','cirugia','emergencia','seguimiento')")
                        .HasColumnName("tipo_cita")
                        .HasDefaultValueSql("'consulta'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId", "FechaCita" }, "idx_doctor_fecha");

                    b.HasIndex(new[] { "Estado" }, "idx_estado");

                    b.HasIndex(new[] { "FechaCita" }, "idx_fecha");

                    b.HasIndex(new[] { "MascotaId" }, "mascota_id");

                    b.HasIndex(new[] { "MetodoPagoId" }, "metodo_pago_id");

                    b.HasIndex(new[] { "SecretariaId" }, "secretaria_id");

                    b.HasIndex(new[] { "DoctorId", "FechaCita", "HoraCita" }, "unique_cita_doctor")
                        .IsUnique();

                    b.ToTable("citas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Nota")
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Identificacion" }, "identificacion")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Apellido", "Email" }, "idx_Busqueda_clientes");

                    b.HasIndex(new[] { "Nombre", "Apellido" }, "idx_nombre");

                    b.HasIndex(new[] { "Telefono" }, "idx_telefono");

                    b.ToTable("clientes", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("FechaConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_consulta")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("mascota_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PesoActual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_actual");

                    b.Property<string>("Receta")
                        .HasColumnType("text")
                        .HasColumnName("receta");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sintomas");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("temperatura");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("text")
                        .HasColumnName("tratamiento");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CitaId" }, "cita_id");

                    b.HasIndex(new[] { "DoctorId" }, "doctor_id");

                    b.HasIndex(new[] { "FechaConsulta" }, "idx_fecha_consulta");

                    b.HasIndex(new[] { "MascotaId" }, "idx_mascota");

                    b.ToTable("consultas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AplicadoPor")
                        .HasColumnType("int(11)")
                        .HasColumnName("aplicado_por");

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Dosis")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dosis");

                    b.Property<string>("Duracion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("duracion");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("frecuencia");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("text")
                        .HasColumnName("instrucciones");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<string>("ViaAdministracion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("via_administracion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AplicadoPor" }, "aplicado_por");

                    b.HasIndex(new[] { "ConsultaId" }, "idx_consulta_producto");

                    b.HasIndex(new[] { "ProductoId" }, "producto_id");

                    b.ToTable("consultas_productos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.DetallesFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ProductosConsultasId")
                        .HasColumnType("int(11)")
                        .HasColumnName("productos_consultas_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FacturaId" }, "idx_factura");

                    b.HasIndex(new[] { "ProductoId" }, "producto_id")
                        .HasDatabaseName("producto_id1");

                    b.HasIndex(new[] { "ProductosConsultasId" }, "productos_consultas_id");

                    b.ToTable("detalles_factura", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int(11)")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<decimal?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("descuento")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pendiente','pagada','cancelada')")
                        .HasColumnName("estado_pago")
                        .HasDefaultValueSql("'pendiente'");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("mascota_id");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("enum('efectivo','tarjeta','transferencia','pago movil','otro')")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("secretaria_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("UrlDocx")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("url_docx");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConsultaId" }, "consulta_id");

                    b.HasIndex(new[] { "ClienteId" }, "idx_cliente_factura");

                    b.HasIndex(new[] { "EstadoPago" }, "idx_estado_pago");

                    b.HasIndex(new[] { "FechaEmision", "EstadoPago" }, "idx_factura_fecha");

                    b.HasIndex(new[] { "FechaEmision" }, "idx_fecha_emision");

                    b.HasIndex(new[] { "MascotaId" }, "mascota_id")
                        .HasDatabaseName("mascota_id1");

                    b.HasIndex(new[] { "NumeroFactura" }, "numero_factura")
                        .IsUnique();

                    b.HasIndex(new[] { "SecretariaId" }, "secretaria_id")
                        .HasDatabaseName("secretaria_id1");

                    b.ToTable("facturas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.FacturaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("GenerateEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FacturaConfigs");
                });

            modelBuilder.Entity("vet_api_Net.Models.HistorialPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<decimal>("PrecioAnterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_anterior");

                    b.Property<decimal>("PrecioNuevo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_nuevo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductoId", "FechaCambio" }, "idx_producto_fecha");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id");

                    b.ToTable("historial_precios", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.LogsSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("json")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("DatosPrevios")
                        .HasColumnType("json")
                        .HasColumnName("datos_previos");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int(11)")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_fecha_log");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_usuario_log");

                    b.ToTable("logs_sistema", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<string>("Alergias")
                        .HasColumnType("text")
                        .HasColumnName("alergias");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int(11)")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<string>("CondicionesMedicas")
                        .HasColumnType("text")
                        .HasColumnName("condiciones_medicas");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("enum('perro','gato')")
                        .HasColumnName("especie");

                    b.Property<bool?>("Esterilizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esterilizado")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("IdenteficacionMascota")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identeficacion_mascota");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("enum('macho','hembra')")
                        .HasColumnName("sexo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdenteficacionMascota" }, "identeficacion_mascota")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Especie", "Raza" }, "idx_Busqueda_mascotas");

                    b.HasIndex(new[] { "ClienteId" }, "idx_cliente_id");

                    b.HasIndex(new[] { "Nombre" }, "idx_nombre_mascota");

                    b.ToTable("mascotas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("emisor_id");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<bool?>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("leido")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("receptor_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("mensajes", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique()
                        .HasDatabaseName("nombre1");

                    b.ToTable("metodos_pago", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.MoneyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BcvDollar")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoneyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MoneyTypes");
                });

            modelBuilder.Entity("vet_api_Net.Models.MovimientosInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_movimiento")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("referencia_id");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock_anterior");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock_nuevo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("enum('entrada','salida','ajuste')")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FechaMovimiento" }, "idx_fecha_movimiento");

                    b.HasIndex(new[] { "ProductoId" }, "idx_producto_movimiento");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id1");

                    b.ToTable("movimientos_inventario", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_venta");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("proveedor");

                    b.Property<bool?>("RequiereReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requiere_receta")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("stock")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("stock_minimo")
                        .HasDefaultValueSql("'5'");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('medicamento','alimento','accesorio')")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unidad_medida")
                        .HasDefaultValueSql("'unidad'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoriaId" }, "categoria_id");

                    b.HasIndex(new[] { "Codigo" }, "codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Codigo", "CategoriaId" }, "idx_Busqueda_productos");

                    b.HasIndex(new[] { "Nombre" }, "idx_nombre_producto");

                    b.HasIndex(new[] { "Stock" }, "idx_stock");

                    b.ToTable("productos", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.ReporConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("GenerateEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ReporConfigs");
                });

            modelBuilder.Entity("vet_api_Net.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Filtro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneradoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("vet_api_Net.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("Actualizado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("actualizado")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Actualizado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("enum('admin','doctor','secretaria')")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.HasIndex(new[] { "Rol" }, "idx_rol")
                        .HasDatabaseName("idx_rol1");

                    b.ToTable("usuarios", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.Vacuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creado")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int(11)")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly>("FechaVacunacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vacunacion");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lote");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int(11)")
                        .HasColumnName("mascota_id");

                    b.Property<string>("Nota")
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("producto_id");

                    b.Property<DateOnly?>("ProximaDosis")
                        .HasColumnType("date")
                        .HasColumnName("proxima_dosis");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConsultaId" }, "consulta_id")
                        .HasDatabaseName("consulta_id1");

                    b.HasIndex(new[] { "DoctorId" }, "doctor_id")
                        .HasDatabaseName("doctor_id1");

                    b.HasIndex(new[] { "FechaVacunacion" }, "idx_fecha_vacuna");

                    b.HasIndex(new[] { "MascotaId" }, "idx_mascota_vacuna");

                    b.HasIndex(new[] { "ProductoId" }, "producto_id")
                        .HasDatabaseName("producto_id2");

                    b.ToTable("vacunas", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("vet_api_Net.Models.AlertasInterna", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Destinatario")
                        .WithMany("AlertasInternaDestinatarios")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("alertas_internas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "LeidaPorNavigation")
                        .WithMany("AlertasInternaLeidaPorNavigations")
                        .HasForeignKey("LeidaPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("alertas_internas_ibfk_2");

                    b.Navigation("Destinatario");

                    b.Navigation("LeidaPorNavigation");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("CitaDoctors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citas_ibfk_2");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Cita")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.MetodoPago", "MetodoPago")
                        .WithMany("Citas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("citas_ibfk_4");

                    b.HasOne("vet_api_Net.Models.Usuario", "Secretaria")
                        .WithMany("CitaSecretaria")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("citas_ibfk_3");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");

                    b.Navigation("MetodoPago");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cita", "Cita")
                        .WithMany("Consulta")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("Consulta")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Consulta")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_2");

                    b.Navigation("Cita");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "AplicadoPorNavigation")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("AplicadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("consultas_productos_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_productos_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_productos_ibfk_2");

                    b.Navigation("AplicadoPorNavigation");

                    b.Navigation("Consulta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("vet_api_Net.Models.DetallesFactura", b =>
                {
                    b.HasOne("vet_api_Net.Models.Factura", "Factura")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalles_factura_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalles_factura_ibfk_2");

                    b.HasOne("vet_api_Net.Models.ConsultasProducto", "ProductosConsultas")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductosConsultasId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("detalles_factura_ibfk_3");

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("ProductosConsultas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("facturas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("Facturas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("facturas_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Facturas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("facturas_ibfk_2");

                    b.HasOne("vet_api_Net.Models.Usuario", "Secretaria")
                        .WithMany("Facturas")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("facturas_ibfk_4");

                    b.Navigation("Cliente");

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("vet_api_Net.Models.HistorialPrecio", b =>
                {
                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historial_precios_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historial_precios_ibfk_2");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.LogsSistema", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("LogsSistemas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("logs_sistema_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cliente", "Cliente")
                        .WithMany("Mascota")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mascotas_ibfk_1");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mensaje", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Emisor")
                        .WithMany("MensajesEmisor")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("mensajes_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Receptor")
                        .WithMany("MensajesReceptor")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("mensajes_ibfk_2");

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("vet_api_Net.Models.MovimientosInventario", b =>
                {
                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movimientos_inventario_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movimientos_inventario_ibfk_2");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.HasOne("vet_api_Net.Models.CategoriasProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("productos_ibfk_1");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("vet_api_Net.Models.Vacuna", b =>
                {
                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("Vacunas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("vacunas_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("Vacunas")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("vacunas_ibfk_4");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Vacunas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vacunas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("Vacunas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vacunas_ibfk_2");

                    b.Navigation("Consulta");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("vet_api_Net.Models.CategoriasProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.Navigation("ConsultasProductos");

                    b.Navigation("Facturas");

                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Consulta");

                    b.Navigation("Facturas");

                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("vet_api_Net.Models.MetodoPago", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.Navigation("ConsultasProductos");

                    b.Navigation("DetallesFacturas");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("MovimientosInventarios");

                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Usuario", b =>
                {
                    b.Navigation("AlertasInternaDestinatarios");

                    b.Navigation("AlertasInternaLeidaPorNavigations");

                    b.Navigation("CitaDoctors");

                    b.Navigation("CitaSecretaria");

                    b.Navigation("Consulta");

                    b.Navigation("ConsultasProductos");

                    b.Navigation("Facturas");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("LogsSistemas");

                    b.Navigation("MensajesEmisor");

                    b.Navigation("MensajesReceptor");

                    b.Navigation("MovimientosInventarios");

                    b.Navigation("Vacunas");
                });
#pragma warning restore 612, 618
        }
    }
}
