// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vet_api_Net.Data;

#nullable disable

namespace vet_api_Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826194451_AddPermissionDefinitions")]
    partial class AddPermissionDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vet_api_Net.Models.AlertasInterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AccionRequerida")
                        .HasColumnType("boolean")
                        .HasColumnName("accion_requerida");

                    b.Property<bool?>("Completada")
                        .HasColumnType("boolean")
                        .HasColumnName("completada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DestinatarioId")
                        .HasColumnType("integer")
                        .HasColumnName("destinatario_id");

                    b.Property<string>("DestinatarioRol")
                        .HasColumnType("text")
                        .HasColumnName("destinatario_rol");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_lectura");

                    b.Property<DateOnly?>("FechaLimite")
                        .HasColumnType("date")
                        .HasColumnName("fecha_limite");

                    b.Property<bool?>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<int?>("LeidaPor")
                        .HasColumnType("integer")
                        .HasColumnName("leida_por");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Prioridad")
                        .HasColumnType("text")
                        .HasColumnName("prioridad");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTabla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referencia_tabla");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DestinatarioId" }, "destinatario_id");

                    b.HasIndex(new[] { "FechaLimite" }, "idx_fecha_limite");

                    b.HasIndex(new[] { "Leida", "Completada", "Prioridad" }, "idx_pendientes");

                    b.HasIndex(new[] { "DestinatarioRol" }, "idx_rol");

                    b.HasIndex(new[] { "LeidaPor" }, "leida_por");

                    b.ToTable("alertas_internas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.CategoriasProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique();

                    b.ToTable("categorias_productos", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cita");

                    b.Property<TimeOnly>("HoraCita")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_cita");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_pago_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int?>("SecretariaId")
                        .HasColumnType("integer")
                        .HasColumnName("secretaria_id");

                    b.Property<string>("TipoCita")
                        .HasColumnType("text")
                        .HasColumnName("tipo_cita");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DoctorId", "FechaCita" }, "idx_doctor_fecha");

                    b.HasIndex(new[] { "Estado" }, "idx_estado");

                    b.HasIndex(new[] { "FechaCita" }, "idx_fecha");

                    b.HasIndex(new[] { "MascotaId" }, "mascota_id");

                    b.HasIndex(new[] { "MetodoPagoId" }, "metodo_pago_id");

                    b.HasIndex(new[] { "SecretariaId" }, "secretaria_id");

                    b.HasIndex(new[] { "DoctorId", "FechaCita", "HoraCita" }, "unique_cita_doctor")
                        .IsUnique();

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Nota")
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Identificacion" }, "identificacion")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Apellido", "Email" }, "idx_Busqueda_clientes");

                    b.HasIndex(new[] { "Nombre", "Apellido" }, "idx_nombre");

                    b.HasIndex(new[] { "Telefono" }, "idx_telefono");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer")
                        .HasColumnName("cita_id");

                    b.Property<decimal?>("ConsultaPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_consulta");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PesoActual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso_actual");

                    b.Property<string>("Receta")
                        .HasColumnType("text")
                        .HasColumnName("receta");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sintomas");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperatura");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("text")
                        .HasColumnName("tratamiento");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CitaId" }, "cita_id");

                    b.HasIndex(new[] { "DoctorId" }, "doctor_id");

                    b.HasIndex(new[] { "FechaConsulta" }, "idx_fecha_consulta");

                    b.HasIndex(new[] { "MascotaId" }, "idx_mascota");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AplicadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("aplicado_por");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Dosis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosis");

                    b.Property<string>("Duracion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("duracion");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frecuencia");

                    b.Property<string>("Instrucciones")
                        .HasColumnType("text")
                        .HasColumnName("instrucciones");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("ViaAdministracion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("via_administracion");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AplicadoPor" }, "aplicado_por");

                    b.HasIndex(new[] { "ConsultaId" }, "idx_consulta_producto");

                    b.HasIndex(new[] { "ProductoId" }, "producto_id");

                    b.ToTable("consultas_productos", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.DetallesFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ProductosConsultasId")
                        .HasColumnType("integer")
                        .HasColumnName("productos_consultas_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<int?>("VaccineId")
                        .HasColumnType("integer")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VaccineId" }, "idx_detalles_factura_vaccine");

                    b.HasIndex(new[] { "FacturaId" }, "idx_factura");

                    b.HasIndex(new[] { "ProductoId" }, "producto_id")
                        .HasDatabaseName("producto_id1");

                    b.HasIndex(new[] { "ProductosConsultasId" }, "productos_consultas_id");

                    b.ToTable("detalles_factura", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HtmlCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("vet_api_Net.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre" }, "idx_especies_nombre")
                        .IsUnique();

                    b.ToTable("especies", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<decimal?>("Descuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("descuento");

                    b.Property<string>("EstadoPago")
                        .HasColumnType("text")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_factura");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("integer")
                        .HasColumnName("secretaria_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<string>("UrlDocx")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url_docx");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConsultaId" }, "consulta_id");

                    b.HasIndex(new[] { "ClienteId" }, "idx_cliente_factura");

                    b.HasIndex(new[] { "EstadoPago" }, "idx_estado_pago");

                    b.HasIndex(new[] { "FechaEmision", "EstadoPago" }, "idx_factura_fecha");

                    b.HasIndex(new[] { "FechaEmision" }, "idx_fecha_emision");

                    b.HasIndex(new[] { "MascotaId" }, "mascota_id")
                        .HasDatabaseName("mascota_id1");

                    b.HasIndex(new[] { "NumeroFactura" }, "numero_factura")
                        .IsUnique();

                    b.HasIndex(new[] { "SecretariaId" }, "secretaria_id")
                        .HasDatabaseName("secretaria_id1");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<string>("AlertasRiesgoIa")
                        .HasColumnType("text")
                        .HasColumnName("alertas_riesgo_ia");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.Property<string>("NotasVeterinario")
                        .HasColumnType("text")
                        .HasColumnName("notas_veterinario");

                    b.Property<string>("ResumenIa")
                        .HasColumnType("text")
                        .HasColumnName("resumen_ia");

                    b.Property<string>("SugerenciasIa")
                        .HasColumnType("text")
                        .HasColumnName("sugerencias_ia");

                    b.Property<DateTime?>("UltimoAnalisisIa")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_analisis_ia");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MascotaId" }, "idx_hc_mascota");

                    b.ToTable("historias_clinicas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.HistorialPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<decimal>("PrecioAnterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_anterior");

                    b.Property<decimal>("PrecioNuevo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_nuevo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductoId", "FechaCambio" }, "idx_producto_fecha");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id");

                    b.ToTable("historial_precios", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.IaConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<string>("BaseConocimiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_conocimiento");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("ReglasRespuesta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reglas_respuesta");

                    b.HasKey("Id");

                    b.ToTable("ia_conocimientos");
                });

            modelBuilder.Entity("vet_api_Net.Models.LogsSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("DatosPrevios")
                        .HasColumnType("text")
                        .HasColumnName("datos_previos");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_fecha_log");

                    b.HasIndex(new[] { "UsuarioId" }, "idx_usuario_log");

                    b.ToTable("logs_sistema", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<string>("Alergias")
                        .HasColumnType("text")
                        .HasColumnName("alergias");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<string>("CondicionesMedicas")
                        .HasColumnType("text")
                        .HasColumnName("condiciones_medicas");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<int>("EspecieId")
                        .HasColumnType("integer")
                        .HasColumnName("especie_id");

                    b.Property<bool?>("Esterilizado")
                        .HasColumnType("boolean")
                        .HasColumnName("esterilizado");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("IdenteficacionMascota")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identeficacion_mascota");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("raza");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex(new[] { "IdenteficacionMascota" }, "identeficacion_mascota")
                        .IsUnique();

                    b.HasIndex(new[] { "ClienteId" }, "idx_cliente_id");

                    b.HasIndex(new[] { "Nombre" }, "idx_nombre_mascota");

                    b.ToTable("mascotas", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<int>("EmisorId")
                        .HasColumnType("integer")
                        .HasColumnName("emisor_id");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<bool?>("Leido")
                        .HasColumnType("boolean")
                        .HasColumnName("leido");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("integer")
                        .HasColumnName("receptor_id");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("mensajes", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nombre" }, "nombre")
                        .IsUnique()
                        .HasDatabaseName("nombre1");

                    b.ToTable("metodos_pago", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.MoneyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BcvDollar")
                        .HasColumnType("numeric");

                    b.Property<string>("DollarPersistence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MoneyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoneyTypes");
                });

            modelBuilder.Entity("vet_api_Net.Models.MovimientosInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("stock_anterior");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_nuevo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FechaMovimiento" }, "idx_fecha_movimiento");

                    b.HasIndex(new[] { "ProductoId" }, "idx_producto_movimiento");

                    b.HasIndex(new[] { "UsuarioId" }, "usuario_id")
                        .HasDatabaseName("usuario_id1");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.PasswordResetTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiracion");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Token" }, "idx_token")
                        .IsUnique();

                    b.HasIndex(new[] { "UsuarioId" }, "idx_usuario_id");

                    b.ToTable("password_reset_tickets", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.PermissionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "idx_permission_definitions_key")
                        .IsUnique();

                    b.ToTable("permission_definitions", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.PetVaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<string>("ClinicalObservations")
                        .HasColumnType("text")
                        .HasColumnName("clinical_observations");

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DetalleFacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("detalle_factura_id");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Dose")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer")
                        .HasColumnName("mascota_id");

                    b.Property<DateOnly?>("NextDoseDate")
                        .HasColumnType("date")
                        .HasColumnName("next_dose_date");

                    b.Property<string>("PostponementReason")
                        .HasColumnType("text")
                        .HasColumnName("postponement_reason");

                    b.Property<DateTime?>("ReminderDayBeforeSentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reminder_day_before_sent_at");

                    b.Property<DateTime?>("ReminderSevenSentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reminder_seven_sent_at");

                    b.Property<DateTime?>("ReminderThreeSentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reminder_three_sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("VaccineBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("vaccine_batch_id");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasColumnName("vaccine_id");

                    b.Property<decimal?>("WeightAtApplication")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_at_application");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConsultaId" }, "consulta_id")
                        .HasDatabaseName("consulta_id1");

                    b.HasIndex(new[] { "DetalleFacturaId" }, "detalle_factura_id");

                    b.HasIndex(new[] { "DoctorId" }, "doctor_id")
                        .HasDatabaseName("doctor_id1");

                    b.HasIndex(new[] { "MascotaId" }, "idx_pet_vaccination_mascota");

                    b.HasIndex(new[] { "NextDoseDate" }, "idx_pet_vaccination_next_dose");

                    b.HasIndex(new[] { "VaccineBatchId" }, "vaccine_batch_id");

                    b.HasIndex(new[] { "VaccineId" }, "vaccine_id");

                    b.ToTable("pet_vaccinations", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_venta");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proveedor");

                    b.Property<bool?>("RequiereReceta")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_receta");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoriaId" }, "categoria_id");

                    b.HasIndex(new[] { "Codigo" }, "codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Codigo", "CategoriaId" }, "idx_Busqueda_productos");

                    b.HasIndex(new[] { "Nombre" }, "idx_nombre_producto");

                    b.HasIndex(new[] { "Stock" }, "idx_stock");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Datos")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Filtro")
                        .HasColumnType("text");

                    b.Property<string>("GeneradoPor")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("vet_api_Net.Models.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackendExternalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("backend_external_url");

                    b.Property<string>("BcvApiUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("bcv_api_url");

                    b.Property<string>("FrontendUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("frontend_url");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("ResendApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resend_api_key");

                    b.Property<string>("ResendApiUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resend_api_url");

                    b.Property<string>("ResendFromEmail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resend_from_email");

                    b.HasKey("Id");

                    b.ToTable("system_configs");
                });

            modelBuilder.Entity("vet_api_Net.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_permissions_user_id")
                        .IsUnique();

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actualizado");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodeRecoveryExpireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("PasswordRecoveryCode")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.HasIndex(new[] { "Rol" }, "idx_rol")
                        .HasDatabaseName("idx_rol1");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BoosterFrequencyUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booster_frequency_unit");

                    b.Property<int>("BoosterFrequencyValue")
                        .HasColumnType("integer")
                        .HasColumnName("booster_frequency_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EspecieId")
                        .HasColumnType("integer")
                        .HasColumnName("especie_id");

                    b.Property<int>("MinimumAgeWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age_weeks");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.ToTable("vaccines", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.VaccineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("batch_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Laboratory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("laboratory");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date")
                        .HasColumnName("received_date");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VaccineId", "ExpirationDate" }, "idx_batch_vaccine_expiration");

                    b.ToTable("vaccine_batches", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.VaccineSchemeStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dose_number");

                    b.Property<int>("IntervalDaysFromPrevious")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days_from_previous");

                    b.Property<int?>("MinimumAgeWeeksOverride")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age_weeks_override");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage_type");

                    b.Property<int>("VaccineId")
                        .HasColumnType("integer")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "VaccineId" }, "idx_scheme_stage_vaccine");

                    b.ToTable("vaccine_scheme_stages", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.WSMessageAPIData", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("Update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ClientId");

                    b.ToTable("WSMessageAPIData");
                });

            modelBuilder.Entity("vet_api_Net.Models.WorkerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("GenerateEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("generate_enabled");

                    b.Property<string>("IntervalUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interval_unit");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("integer")
                        .HasColumnName("interval_value");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("RetentionUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("retention_unit");

                    b.Property<int?>("RetentionValue")
                        .HasColumnType("integer")
                        .HasColumnName("retention_value");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WorkerName" }, "idx_worker_configs_worker_name")
                        .IsUnique();

                    b.ToTable("worker_configs", (string)null);
                });

            modelBuilder.Entity("vet_api_Net.Models.AlertasInterna", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Destinatario")
                        .WithMany("AlertasInternaDestinatarios")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("alertas_internas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "LeidaPorNavigation")
                        .WithMany("AlertasInternaLeidaPorNavigations")
                        .HasForeignKey("LeidaPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("alertas_internas_ibfk_2");

                    b.Navigation("Destinatario");

                    b.Navigation("LeidaPorNavigation");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("CitaDoctors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citas_ibfk_2");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Cita")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.MetodoPago", "MetodoPago")
                        .WithMany("Citas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("citas_ibfk_4");

                    b.HasOne("vet_api_Net.Models.Usuario", "Secretaria")
                        .WithMany("CitaSecretaria")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("citas_ibfk_3");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");

                    b.Navigation("MetodoPago");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cita", "Cita")
                        .WithMany("Consulta")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("Consulta")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Consulta")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_ibfk_2");

                    b.Navigation("Cita");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "AplicadoPorNavigation")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("AplicadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("consultas_productos_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_productos_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("ConsultasProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("consultas_productos_ibfk_2");

                    b.Navigation("AplicadoPorNavigation");

                    b.Navigation("Consulta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("vet_api_Net.Models.DetallesFactura", b =>
                {
                    b.HasOne("vet_api_Net.Models.Factura", "Factura")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalles_factura_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("detalles_factura_ibfk_2");

                    b.HasOne("vet_api_Net.Models.ConsultasProducto", "ProductosConsultas")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ProductosConsultasId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("detalles_factura_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("detalles_factura_ibfk_4");

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("ProductosConsultas");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("facturas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("Facturas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("facturas_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("Facturas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("facturas_ibfk_2");

                    b.HasOne("vet_api_Net.Models.Usuario", "Secretaria")
                        .WithMany("Facturas")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("facturas_ibfk_4");

                    b.Navigation("Cliente");

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("vet_api_Net.Models.HistoriaClinica", b =>
                {
                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("HistoriasClinicas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historia_clinica_mascota");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("vet_api_Net.Models.HistorialPrecio", b =>
                {
                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historial_precios_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historial_precios_ibfk_2");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.LogsSistema", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("LogsSistemas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("logs_sistema_ibfk_1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.HasOne("vet_api_Net.Models.Cliente", "Cliente")
                        .WithMany("Mascota")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mascotas_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Especie", "Especie")
                        .WithMany("Mascotas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("mascotas_ibfk_2");

                    b.Navigation("Cliente");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mensaje", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Emisor")
                        .WithMany("MensajesEmisor")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("mensajes_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Receptor")
                        .WithMany("MensajesReceptor")
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("mensajes_ibfk_2");

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("vet_api_Net.Models.MovimientosInventario", b =>
                {
                    b.HasOne("vet_api_Net.Models.Producto", "Producto")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movimientos_inventario_ibfk_1");

                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movimientos_inventario_ibfk_2");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.PasswordResetTicket", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "Usuario")
                        .WithMany("PasswordResetTickets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vet_api_Net.Models.PetVaccination", b =>
                {
                    b.HasOne("vet_api_Net.Models.Consulta", "Consulta")
                        .WithMany("PetVaccinations")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pet_vaccinations_ibfk_4");

                    b.HasOne("vet_api_Net.Models.DetallesFactura", "DetalleFactura")
                        .WithMany()
                        .HasForeignKey("DetalleFacturaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pet_vaccinations_ibfk_6");

                    b.HasOne("vet_api_Net.Models.Usuario", "Doctor")
                        .WithMany("PetVaccinations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pet_vaccinations_ibfk_5");

                    b.HasOne("vet_api_Net.Models.Mascota", "Mascota")
                        .WithMany("PetVaccinations")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pet_vaccinations_ibfk_1");

                    b.HasOne("vet_api_Net.Models.VaccineBatch", "VaccineBatch")
                        .WithMany("PetVaccinations")
                        .HasForeignKey("VaccineBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("pet_vaccinations_ibfk_3");

                    b.HasOne("vet_api_Net.Models.Vaccine", "Vaccine")
                        .WithMany("PetVaccinations")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pet_vaccinations_ibfk_2");

                    b.Navigation("Consulta");

                    b.Navigation("DetalleFactura");

                    b.Navigation("Doctor");

                    b.Navigation("Mascota");

                    b.Navigation("Vaccine");

                    b.Navigation("VaccineBatch");
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.HasOne("vet_api_Net.Models.CategoriasProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("productos_ibfk_1");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("vet_api_Net.Models.UserPermission", b =>
                {
                    b.HasOne("vet_api_Net.Models.Usuario", "User")
                        .WithOne("UserPermission")
                        .HasForeignKey("vet_api_Net.Models.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vet_api_Net.Models.Vaccine", b =>
                {
                    b.HasOne("vet_api_Net.Models.Especie", "Especie")
                        .WithMany("Vaccines")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("vaccines_ibfk_1");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("vet_api_Net.Models.VaccineBatch", b =>
                {
                    b.HasOne("vet_api_Net.Models.Vaccine", "Vaccine")
                        .WithMany("Batches")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vaccine_batches_ibfk_1");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("vet_api_Net.Models.VaccineSchemeStage", b =>
                {
                    b.HasOne("vet_api_Net.Models.Vaccine", "Vaccine")
                        .WithMany("SchemeStages")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vaccine_scheme_stages_ibfk_1");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("vet_api_Net.Models.CategoriasProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("vet_api_Net.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("vet_api_Net.Models.Consulta", b =>
                {
                    b.Navigation("ConsultasProductos");

                    b.Navigation("Facturas");

                    b.Navigation("PetVaccinations");
                });

            modelBuilder.Entity("vet_api_Net.Models.ConsultasProducto", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Especie", b =>
                {
                    b.Navigation("Mascotas");

                    b.Navigation("Vaccines");
                });

            modelBuilder.Entity("vet_api_Net.Models.Factura", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Mascota", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Consulta");

                    b.Navigation("Facturas");

                    b.Navigation("HistoriasClinicas");

                    b.Navigation("PetVaccinations");
                });

            modelBuilder.Entity("vet_api_Net.Models.MetodoPago", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("vet_api_Net.Models.Producto", b =>
                {
                    b.Navigation("ConsultasProductos");

                    b.Navigation("DetallesFacturas");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("MovimientosInventarios");
                });

            modelBuilder.Entity("vet_api_Net.Models.Usuario", b =>
                {
                    b.Navigation("AlertasInternaDestinatarios");

                    b.Navigation("AlertasInternaLeidaPorNavigations");

                    b.Navigation("CitaDoctors");

                    b.Navigation("CitaSecretaria");

                    b.Navigation("Consulta");

                    b.Navigation("ConsultasProductos");

                    b.Navigation("Facturas");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("LogsSistemas");

                    b.Navigation("MensajesEmisor");

                    b.Navigation("MensajesReceptor");

                    b.Navigation("MovimientosInventarios");

                    b.Navigation("PasswordResetTickets");

                    b.Navigation("PetVaccinations");

                    b.Navigation("UserPermission");
                });

            modelBuilder.Entity("vet_api_Net.Models.Vaccine", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("PetVaccinations");

                    b.Navigation("SchemeStages");
                });

            modelBuilder.Entity("vet_api_Net.Models.VaccineBatch", b =>
                {
                    b.Navigation("PetVaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
